mvel/mvel

src/main/java/org/mvel2/compiler/AbstractParser.java
src/main/java/org/mvel2/optimizers/impl/asm/ASMAccessorOptimizer.java
src/main/java/org/mvel2/sh/ShellSession.java
src/main/java/org/mvel2/util/ParseTools.java
src/main/java/org/mvel2/util/PropertyTools.java

Mainly for android support as Android 5.0 doesn't allow System.setProperty("java.version", ...)

[DROOLS-729] - accept mvel.java.version override for java.version system property

---

src/main/java/org/mvel2/optimizers/OptimizerFactory.java

The exception is:
2015-07-24 16:17:08,616 ERROR [stderr] (default task-1) java.lang.NullPointerException
2015-07-24 16:17:08,617 ERROR [stderr] (default task-1) 	at org.mvel2.optimizers.OptimizerFactory.<clinit>(OptimizerFactory.java:45)
2015-07-24 16:17:08,617 ERROR [stderr] (default task-1) 	at org.mvel2.ast.ASTNode.optimize(ASTNode.java:145)
2015-07-24 16:17:08,617 ERROR [stderr] (default task-1) 	at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:115)
2015-07-24 16:17:08,617 ERROR [stderr] (default task-1) 	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:42)
2015-07-24 16:17:08,617 ERROR [stderr] (default task-1) 	at org.mvel2.MVEL.executeExpression(MVEL.java:969)

Fix NPE when using mvel compiled expression from bootstrap classloader

---

src/main/java/org/mvel2/optimizers/impl/asm/ASMAccessorOptimizer.java
src/test/java/org/mvel2/tests/core/PropertyAccessTests.java

Caused when accessing the element of an element of a null collection.
See the new unit tests testInfiniteLoopWithASMOptimizer() and
testInfiniteLoopWithASMOptimizerAO() for details

avoid infinite loop on ASM optimizer

---

src/main/java/org/mvel2/compiler/AbstractParser.java
src/main/java/org/mvel2/util/ParseTools.java

* versioning scheme changed in Java 9
* some code was removed because it cheched for Java
version < 1.5, which is no longer supported
(source + target version is set to 1.5). Also the code
would never be executed anyway since the JVM would
fail to load the class compiled for newer version of Java
@mariofusco please take a look

Fixes for Java 9

---

src/main/java/org/mvel2/util/ParseTools.java
src/test/java/org/mvel2/tests/core/CoreConfidenceTests.java
src/test/java/org/mvel2/tests/core/res/OverloadedInterface.java
src/test/java/org/mvel2/tests/core/res/res2/OverloadedClass.java

I found a case when ParseTools.getExactMatch function doesn't return proper method. Test case attached and the logic flaw there is pretty obvious (when iterating through the arguments it should make sure they are all equal and not return null on first difference because there may be a better overloaded method)
I found this being a root cause of a production problem I had when this method was called from a getWidenedTarget after an IllegalAccessException in PropertyAccessor.getMethod. The exception was thrown correctly (the method in the class was marked as package private so it wasn't visible indeed) but the handling failed due to above getExactMatch problem.

Fix case with overloaded methods.

---

src/main/java/org/mvel2/optimizers/impl/asm/ASMAccessorOptimizer.java

We came across the problem mentioned in https://github.com/mikebrock/mvel/issues/27
and unfortunately, we cannot move to latest version of MVEL2.  We tried with below change and it works for us with Java 8. Is this something we can release part of 2.1.X releases, may be as 2.1.10.Final?  And unfortunately, I am not finding any branch associated to 2.1. releases but can see tags. Please let me know if you are fine with this change but re-create PR against a different branch.

Fix for https://github.com/mikebrock/mvel/issues/27

---

src/main/java/org/mvel2/optimizers/impl/asm/ASMAccessorOptimizer.java
src/test/java/org/mvel2/tests/core/osgi/AsmOptimizerOsgiTest.java

This pull request fixes problem in OSGI environment when optimizer kicks in and collection API is used.
Test, which reproduces problem is provided.
Stack trace for the exception:
```
java.lang.ClassNotFoundException: org.mvel2.compiler.Accessor
at java.lang.ClassLoader.findClass(ClassLoader.java:531)[:1.7.0_95]
at java.lang.ClassLoader.loadClass(ClassLoader.java:425)[:1.7.0_95]
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)[:1.7.0_95]
at java.lang.ClassLoader.defineClass1(Native Method)[:1.7.0_95]
at java.lang.ClassLoader.defineClass(ClassLoader.java:800)[:1.7.0_95]
at java.lang.ClassLoader.defineClass(ClassLoader.java:643)[:1.7.0_95]
at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer$ContextClassLoader.defineClass(ASMAccessorOptimizer.java:2232)
at …
```

Preserve parser context when optimizing collections

---

src/main/java/org/mvel2/optimizers/impl/refl/nodes/FieldAccessor.java
src/main/java/org/mvel2/optimizers/impl/refl/nodes/FieldAccessorNH.java
src/main/java/org/mvel2/optimizers/impl/refl/nodes/MethodAccessor.java
src/main/java/org/mvel2/optimizers/impl/refl/nodes/SetterAccessor.java
src/test/java/org/mvel2/tests/perftests/SetterAccessorConcurrencyTest.java

This pull request fixes concurrency problem in SetterAccessor class when optimization kicks in.
See details in following issue: https://github.com/mvel/mvel/issues/98

Preserve coercion flag for exception block to avoid concurrency issue

---

src/main/java/org/mvel2/integration/PropertyHandlerFactory.java
src/test/java/org/mvel2/tests/core/PropertyHandlerTests.java

Consider the following two classes A and B.
```java
public class A implements Serializable {
// ...
}
public class B implements Serializable {
// ...
}
```
If a custom PropertyHandler is registered to `A`, it is also registered to its interface `Serializable`.
This causes a problem when accessing properties of `B` using pre-compiled expression (please see the attached test case).
If the PropertyHandler is registered to the common interface `Serializable`, it should be applied to both `A` and `B`, of course.
There was a similar report in the mailing list, but it got no reply.
http://markmail.org/message/7yxd5xmkbiccmlfr

Property handler should not be auto-registered recursively.

---

src/main/java/org/mvel2/optimizers/impl/refl/nodes/DynamicFunctionAccessor.java
src/test/java/org/mvel2/tests/core/FunctionsTest.java
src/test/java/org/mvel2/tests/core/res/Member.java
src/test/java/org/mvel2/tests/core/res/SharedFuncLib.java

In my project I wanted to create reusable library of mvel functions - see SharedFuncLib class for example.
When I try to use shared functions in multithreaded environment I get ClassCasetException - cannot cast FunctionInstance to fuction.
This happens only if I have complex function, like function that accepts clousure, which in turn uses other functions.
The same issue was reported for muel-mvel fork and fixed in exactly the same way for older version of mvel.
Please let me know if there is something wrong with my approach to create reusable set of mvel functions, or provided fix is proper solution.

Fix for ClassCastException when trying to reuse complex functions in multithreaded scenario

---

src/main/java/org/mvel2/ast/ASTNode.java
src/test/java/org/mvel2/compiler/MvelCompileExpNullSafeTest.java

This scenario is failing in JBPM :
When there is an ASTNode with deep property ($.firstName), the custom VariableResolver may receive a null string to deal with it.
My proposal is to check if nameCache is not null, before invoking isResolveable.

[JBPM-8900] Check name is not null before invoking isResolveable

---

src/main/java/org/mvel2/optimizers/impl/asm/ASMAccessorOptimizer.java
src/test/java/org/mvel2/tests/core/CoreConfidenceTests.java

- Use original ctx rather than collection ctx in getCollectionProperty
- Remove problematic optimization in addSubstatement since it assumes that the index is either litteral or in the VariableResolver
- Add unit test to demonstrate issue and fix

Issue181 - Nested property access successful in ReflectiveAccessorOptimizer but fails in ASMAccessorOptimizer

---

src/main/java/org/mvel2/asm/SymbolTable.java
src/test/java/org/mvel2/tests/core/CoreConfidenceTests.java

In SymbolTable.addConstant(), for unimplemented cases, throw OptimizationNotSupported instead of IllegalArgumentException to allow normal processing.

Issue89 - IllegalArgumentException in org.mvel2.asm.ClassWriter

---

src/main/java/org/mvel2/util/ParseTools.java
src/test/java/org/mvel2/tests/core/ArithmeticTests.java

Fix a bug in JDK 8:
s1=0B;s1+=1;s1+=1;s1  will get wrong result 11
while process the first s1+=1(BigDecimal(0) + Integer(1)), BigDecimal(0).add(InternalNumber(1)) -> InternalNumber(1)
and then process the second s1+=1(InternalNumber(1) + Integer(1)), Object + Integer, process as string append, get result 11.
add InternalNumber class in typeCodes map could fix this problem.

Fix __resolveType process InternalNumber as Object

---

src/main/java/org/mvel2/optimizers/impl/asm/ASMAccessorOptimizer.java
src/main/java/org/mvel2/optimizers/impl/refl/ReflectiveAccessorOptimizer.java
src/main/java/org/mvel2/optimizers/impl/refl/nodes/MapAccessorNest.java
src/test/java/org/mvel2/tests/core/CoreConfidenceTests.java

Fixes #226 
Main fix:
The previous way to evaluate expressions in square brackets using ThisValueAccessor had a serious side effect because it was using the map to the left as context rather than the object passed as "this". I'm reverting this and adding code to properly evaluate the sub-expression: Use thisRef to compile sub-expression in ReflectiveAccessorOptimizer and use elCtx rather than ctx in MapAccessorNest.
Also found that the fix for #181 had to be duplicated for cases where COMPILER_OPT_ALLOW_OVERRIDE_ALL_PROPHANDLING is set to true.

Issue226 Fix nested expression implementation

---

src/main/java/org/mvel2/compiler/AbstractParser.java
src/test/java/org/mvel2/tests/core/CoreConfidenceTests.java
src/test/java/org/mvel2/tests/core/WithTests.java

Fixes #222 
The existing call to skipWhitespace() after the dot in captureToEOT() apparently attempted to skip the spaces after the dot but it didn't do anything since the cursor was not on a space. This meant that the following space ended the token (in the "default:" case of the next iteration).
The change is to skip the spaces after the dot, then go back by one position (since the loop will increment again in the while() instruction). Failing to decrement would break a bunch of tests using ".{" constructs.

Issue222 Incorrect parsing of some expressions with spaces after dot

---

src/main/java/org/mvel2/optimizers/impl/asm/ASMAccessorOptimizer.java
src/test/java/org/mvel2/tests/core/CoreConfidenceTests.java

Fixes #217 
After calling skipWhitespace() we can no longer rely on the length attribute since it's relative to the cursor which might have been incremented. 
I went with a localized fix to rely on 'end' rather than 'length', since is not relative to the cursor.
I considered changing skipWhitespace() to update the length but given the amount of calls to it there is a high risk of introducing more bugs (For example, it would break ReflectiveAccessOptimizer.optimizeSetAccessor()). I'm open to doing it that way if we're confident about all the calls.

Issue217 CoreConfidenceTests.testMethodCallWithSpaces() fails under ASM

---

src/test/java/org/mvel2/tests/core/DebuggerTests.java

Fixes #215 
Clear global breakpoints before each test so that the breakpoints of one test doesn't affect another test

Issue215 DebuggerTests fails sporadically

---

src/main/java/org/mvel2/optimizers/impl/asm/ASMAccessorOptimizer.java
src/test/java/org/mvel2/tests/core/ASMConsistencyTest.java

Issue is caused by a race condition when sometimes the "contains" call is optimized to ASM by ASMAccessorOptimizer.getMethod() before the ArrayList is optimized to FastList. When the ASM-generated class is invoked later, it will fail because the collection is now a FastList and the generated code contains a CHECKCAST for the original class (ArrayList). However, in ASMAccessorOptimizer.getMethod(), the method has been widened to Collection.contains but the CHECKCAST is still created based on the original class. The fix is to create the CHECKCAST based on the method's declaring class.

Issue113 - mvel throw FastList casting exception under high concurrency

---

src/main/java/org/mvel2/util/ParseTools.java
src/test/java/org/mvel2/tests/core/CoreConfidenceTests.java

- [DROOLS-5284] MVELTest.testTypeCoercionLongDivByInt fails with IBM JDK 8
See comment in https://issues.redhat.com/browse/DROOLS-5284
This PR adds isMorePreciseForBigDecimal() so Math.round(double) is prioritized over Math.round(float). This may not have to be specific to BigDecimal case but I wanted to keep the change minimal.

Improve getBestCandidate() for BigDecimal args

---

src/main/java/org/mvel2/ast/TypeCast.java

As it was written, the error message here would always say "cannot be cast to java.lang.Class", rather than referring to the actual target class name.
As a side note, I'm not sure why this is not just using `type.cast(inst)` instead of rewriting what I think is an equivalent check.

Fix error message in `ClassCastException`

---

.classpath
src/main/java/org/mvel2/optimizers/impl/asm/ASMAccessorOptimizer.java
src/test/java/org/mvel2/tests/core/CoreConfidenceTests.java

Fixes #182 
Fixed the vararg constructor issue by pushing an empty array of the correct type.
Also fixed a bug in the vararg method call but this was silently handled by switching to interpreted mode: The previous attempt to handle empty vararg would add an ExecutableLiteral as the last parameter but there is no support to add a constant of type array in  visitLdcInsn so we'd end up in the exception catch that switches to interpreted mode. I removed that code and instead added the empty array after looping (same solution as vararg constructor).
Also removed a couple of duplicate evaluations around the same code.

Issue182 constructor vararg support

---

src/main/java/org/mvel2/util/ParseTools.java
src/test/java/org/mvel2/tests/core/VarargTests.java

Non-varargs constructor should have priority over varargs constructors having the same score. Also applied decimal precision priority.

Make constructor priority more consistent with method priority regarding vararg

---

src/main/java/org/mvel2/PropertyAccessor.java

Fixes #282 
This fixes a case that can happen in real life (not just unit tests): When a getter is declared in an interface and implemented in a private class, invoking it will fail when running in Java 17+. This happens for example with Map.Entry.getKey() and Map.Entry.getValue(). If we find that the invokation failed and the method can be found in a parent interface, then call the method in the interface.

Issue282 - Build fails under Java 17 because of module access restrictions

---

src/main/java/org/mvel2/util/ErrorUtil.java
src/test/java/org/mvel2/tests/core/FailureTests.java

https://kie.zulipchat.com/#narrow/stream/232678-jbpm/topic/WorkItemHandler
https://issues.redhat.com/browse/DROOLS-7428
The problem is that ErrorUtil throws NPE when `caught.getExpr()` is null, so the call cannot get the root cause of the `CompileException`.
It is reported for business-central, but this should be fixed for general use cases.

[DROOLS-7428] ErrorUtil should not throw NPE

---

src/main/java/org/mvel2/CompileException.java
src/test/java/org/mvel2/tests/core/CompileExceptionTest.java

Hi, this PR is a solution for issue #312 .
When creating a CompileException, the input cursor might be less than 0, which leads to a StringIndexOutOfBoundException thrown when calling its toString() method. Since it can be hard for MVEL users to notice this potential throwing of exception, I think it might be the best way to just eliminate this possibility inside the MVEL code rather than letting users to catch it. This commit solves this by adding a defensive judgement to make it at least 0.

Add a defensive judgement of cursor

---

src/main/java/org/mvel2/util/ParseTools.java
src/test/java/org/mvel2/tests/core/ParseToolsTest.java

Fix the bug mentioned in issue #315 . Full analysis can be checked in the issue's comments.

Fix parse tool cannot identify string escape

---

src/main/java/org/mvel2/integration/impl/ClassImportResolverFactory.java
src/main/java/org/mvel2/integration/impl/IndexVariableResolver.java
src/main/java/org/mvel2/integration/impl/IndexedVariableResolverFactory.java
src/main/java/org/mvel2/integration/impl/SimpleSTValueResolver.java
src/main/java/org/mvel2/util/SimpleVariableSpaceModel.java
src/test/java/org/mvel2/tests/core/TypesAndInferenceTests.java

https://issues.redhat.com/browse/DROOLS-7540
This is a fix to solve test cases in https://github.com/kiegroup/drools/pull/5498
Drools uses `SimpleVariableSpaceModel` to create `IndexedVariableResolverFactory`. What this PR does are
* Use `SimpleSTValueResolver` instead of `SimpleValueResolver` to enable coercion
* Enhance `IndexVariableResolver` to enable coercion

[DROOLS-7540] Coercion from Interger literal to BigDecimal bind variable

---

src/test/java/org/mvel2/tests/core/ControlFlowTests.java
src/test/java/org/mvel2/tests/core/res/PDFFieldUtil.java

- Fix test not to depend on System.currentTimeMillis()

[mvel-352] ControlFlowTests.testCalculateAge fails

---

pom.xml
src/test/java/org/mvel2/marshalling/MarshallingTest.java

- Actually, xstream is not used, so we can remove it
xstream seemed to be experimented in the past. But finally, removed from the code base. Just the pom dependency and commented-out codes remain now.
- https://github.com/mvel/mvel/issues/359

[mvel-359] xstream CVEs -- remove xstream
